### ISSUE TITLE
Advanced search (query builder)

### ISSUE THREAD

**Issue by brehaut** [AdventureLookup/adventurelookup-frontend#10]
This third search UI is the most involved to create: It will produce an 'advanced search' UI where the user selects fields from dropdowns or sets of available options, and then gets appropriate UI for the value. 

It needs to be a composable UI that can perform boolean operations (and, or, not) and grouping. The different fields will have different content types which will require different UIs to provide the data.

This is the most intensive of the search UIs but likely the most powerful for the largest portion of users.

In the context of this ticket the query is the entire search string, a sub query is any particular subsection of that query that could be considered a query in its own right, a facet is an intrinsic or user defined field of an entry, and a constraint is value used to search a particular facet or facets of the data.
- [ ] Add a constraint across any facet (anything that mentions _elves_)
  - [ ] Autocomplete the facet values
- [ ] Add a constraint for a specific facet (_setting_ is _Collabris_)
  - [ ] Autocomplete the facet name
  - [ ] Autocomplete the facet value for the given facet name
- [ ] Sub queries that can be joined with a boolean operation:
  - [ ] _Not_ some sub query.
  - [ ] _And_ all the sub queries.
  - [ ] _Or_ any one of the sub queries.
- [ ] Integrate with the middleware. ( #4 )
- [ ] Integrate with the common search UI interface. ( #6 )
- [ ] Optional bonus: 
  - [ ] Generate a textual equivalent of the query using the infrastructure of the parser UI ( #9 )
  - [ ] Generate a query builder value from a parser UI
    - [ ] Do it dynamically as the user types.

Depends on #4, #6, #9

**Comment by brehaut** [comment]
CC: @brehaut, @neorapsta
